#ifndef COMMON_CORE_VERSION_H_
#define COMMON_CORE_VERSION_H_
#include <stdint.h> // uint32_t
#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

/**
 * Interface to code-generated version data. This is generated by cmake.
 * It will be regenerated on each build, but because its data is in a .c
 * file it shouldn't incur much other than a relink.
 *
 * */
// The size of a git-describe short sha with a nul terminator to avoid
// fooling anybody
#define VERSION_SHORTSHA_SIZE 8
struct version {
    uint32_t version;
    char sha[VERSION_SHORTSHA_SIZE];
};

const struct version* version_get();

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
#endif // defined COMMON_CORE_VERSION_H
