name: ot3-firmware Repo Setup
description: Setup for ot3-firmware Github Actions

inputs:
  cache-version:
    description: CACHE_VERSION from secrets
    required: true

runs:
  using: composite
  steps:
    - name: Update and install gcc-10 & g++-10
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y gcc-10 g++-10

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache STM32 Tools
      uses: actions/cache@v3
      id: cache-tools
      with:
        path: ${{ env.DEFAULT_DIRECTORY }}/stm32-tools
        key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ inputs.cache-version }}

    - name: Setup opentrons monorepo
      uses: actions/checkout@v4
      with:
        repository: opentrons/opentrons
        path: opentrons
