name: "Common build/test"
on:
  pull_request:
    paths:
      - "common/**"
      - "include/common/**"
      - "cmake/*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
    paths_ignore:
      - "cmake/Arduino*"
  push:
    paths:
      - "common/**"
      - "include/common/**"
      - "cmake/*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/common.yaml"
    paths_ignore:
      - "cmake/Arduino*"
    branches:
      - "*"
    tags:
      - "common@*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  cross-compile-check:
    name: "Cross-Compile/Check"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/setup-python@v2"
        with:
          python-version: '3.7'
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v2"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=cross .
      - name: "Format"
        run: cmake --build ./build-cross --target common-format-ci
        # TODO (AL 2021-07-09) - uncomment when adding common-lint is added
#      - name: "Lint"
#        run: cmake --build ./build-cross --target common-lint
      - name: "Build"
        run: cmake --build ./build-cross --target common
  host-compile-test:
    name: "Host-Compile/Test"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/setup-python@v2"
        with:
          python-version: '3.7'
      - run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v2"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=host-gcc10 .
      - name: 'Build and test'
        run: cmake --build ./build-host --target common-build-and-test
