name: "Head build/test"
on:
  pull_request:
    paths:
      - "head/**"
      - "common/**"
      - "can/**"
      - "spi/**"
      - "motor-control/**"
      - "include/**"
      - "!include/pipettes/**"
      - "!include/gantry/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "CMakeLists.txt"
      - "head/CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
  push:
    paths:
      - "head/**"
      - "common/**"
      - "can/**"
      - "spi/**"
      - "motor-control/**"
      - "include/**"
      - "!include/pipettes/**"
      - "!include/gantry/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "CMakeLists.txt"
      - "head/CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/head.yaml"
    branches:
      - "*"
    tags:
      - "head@*"
  workflow_dispatch:

env:
  ci: 1

defaults:
  run:
    shell: bash

jobs:
  cross-compile-check:
    name: "Cross-Compile/Check"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v2"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=cross . -DCMAKE_BUILD_TYPE=debug
      - name: "Format"
        run: cmake --build ./build-cross --target head-format-ci
      - name: "Build"
        run: cmake --build ./build-cross --target head-exes head-images
      - name: "Lint"
        run: cmake --build ./build-cross --target head-lint
      - name: "Upload proto artifacts"
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: "head-proto-${{github.ref_name}}"
          path: |
            build-cross/head/firmware/head-proto
            build-cross/head/firmware/head-proto-image.hex
      - name: "Upload rev1 artifacts"
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: "head-rev1-${{github.ref_name}}"
          path: |
            build-cross/head/firmware/head-rev1
            build-cross/head/firmware/head-rev1-image.hex
      - name: "Upload default artifacts"
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: "head-${{github.ref_name}}"
          path: |
            build-cross/head/firmware/head
            build-cross/head/firmware/head-image.hex
  host-compile-test:
    name: "Host-Compile/Test"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - name: Update and install gcc-10 & g++-10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Checkout ot3-firmware repository
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          path: ot3-firmware

      - name: Checkout opentrons repository
        uses: actions/checkout@v3
        with:
          repository: "Opentrons/opentrons"
          path: opentrons

      - name: Cache stm32-tools
        uses: "actions/cache@v2"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}

      - name: "Configure"
        run: cmake --preset=host-gcc10 .
        working-directory: ot3-firmware

      - name: 'Build and test'
        run: cmake --build ./build-host --target head-build-and-test
        working-directory: ot3-firmware

      - name: 'Setup ot3_state_manager'
        run: cmake --build ./build-host/ --target ot3-state-manager-setup
        working-directory: ot3-firmware

      - name: 'Build simulator'
        run: cmake --build ./build-host --target head-simulator
        working-directory: ot3-firmware

      - name: 'Upload artifacts'
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: "head-simulator-${{github.ref_name}}"
          path: |
            build-host/head/simulator/head-simulator
