name: "motor-control build/test"
on:
  pull_request:
    paths:
      - "motor-control/**"
      - "include/motor-control/**"
      - "cmake/*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
    paths_ignore:
      - "cmake/Arduino*"
  push:
    paths:
      - "motor-control/**"
      - "include/motor-control/**"
      - "cmake/*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/common.yaml"
    paths_ignore:
      - "cmake/Arduino*"
    branches:
      - "*"
    tags:
      - "motor-control@*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  host-compile-test:
    name: "Host-Compile/Test"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/setup-python@v2"
        with:
          python-version: '3.7'
      - run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v2"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=host-gcc10 .
      - name: "Format check"
        run: cmake --build ./build-host --target motor-control-format-ci
      - name: "Build and test"
        run cmake --build ./build-host --target motor-control-build-and-test
      - name: "Lint"
        run: cmake --build ./build-host --target lint
