name: "rear-panel build/test"
on:
  pull_request:
    paths:
      - "rear-panel/**"
      - "include/rear-panel/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "include/common/**"
      - "common/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
  push:
    paths:
      - "rear-panel/**"
      - "include/rear-panel/**"
      - "include/common/**"
      - "common/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/rear-panel.yaml"
    branches:
      - "*"
    tags:
      - "rear-panel@*"
  workflow_dispatch:

env:
  ci: 1

defaults:
  run:
    shell: bash

jobs:
  cross-compile-check:
    name: "Cross-Compile/Check"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v3"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=cross . -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: "Format"
        run: cmake --build ./build-cross --target rear-panel-format-ci
      - name: "Lint"
        run: cmake --build ./build-cross --target rear-panel-lint
      - name: "Build"
        run: cmake --build ./build-cross --target rear-panel-applications
  host-compile-test:
    name: "Host-Compile/Test"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v3"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=host-gcc10 .
      - name: 'Build and test'
        run: cmake --build ./build-host --target rear-panel-build-and-test
