name: "Build firmware release bundles"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:

env:
  ci: 1

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v3"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: 'CMake configure'
        run: |
          cmake --preset=cross . -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: 'Build images'
        run: |
          cmake --build --preset=firmware-g4 --target firmware-images firmware-applications
      - name: 'Prep images for upload'
        run: |
          cmake --install ./build-cross
      - name: 'Upload application artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'firmware-applications-${{github.ref_name}}'
          path: |
            dist/applications/*.hex
      - name: 'Upload all-images artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'firmware-images-${{github.ref_name}}'
          path: |
            dist/images/*.hex
      - name: 'Upload robot-images artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'firmware-robot-images-${{github.ref_name}}'
          path: |
            dist/robot-images/*.hex
      - name: 'Upload pipette-images artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'firmware-pipette-images-${{github.ref_name}}'
          path: |
            dist/pipette-images/*.hex
      - name: 'Upload gripper-images artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'firmware-gripper-images-${{github.ref_name}}'
          path: |
            dist/gripper-images/*.hex
  release:
    name: 'Do a release'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    needs: ['build']
    if: github.ref_type == 'tag'
    steps:
      - name: 'Download artifacts'
        uses: 'actions/download-artifact@v3'
        with:
          path: .
      - name: 'Create a release'
        uses: 'ncipollo/release-action@v1.12.0'
        with:
          artifacts: ./firmware-images-${{github.ref_name}}/*, ./firmware-robot-images-${{github.ref_name}}/*, ./firmware-pipette-images-${{github.ref_name}}/*, ./firmware-gripper-images-${{github.ref_name}}/*
          artifactContentType: application/zip
          draft: true
          generateReleaseNotes: true
          replacesArtifacts: true
          allowUpdates: true
