on: [push]

jobs:
  ot3-emulator:
    runs-on: "ubuntu-20.04"
    name: OT-3 Emulator
    steps:
      - uses: actions/checkout@v2
      - id: foo
        run: sudo modprobe vcan
        uses: Opentrons/ot3-emulator@v0.1
        with:
          ot3-firmware-commit-id: ${{ github.sha }}