on: [ pull_request, push ]

jobs:
  ot3-emulator:
    runs-on: "ubuntu-20.04"
    name: OT-3 Emulator
    steps:

      - name: Checkout opentrons-emulation repo
        uses: actions/checkout@v3
        with:
          repository: Opentrons/opentrons-emulation
          ref: working-with-other-repos

      - name: Checkout ot3-firmware repo
        uses: actions/checkout@v3
        with:
          path: ot3-firmware

      - name: Debug Time
        run: ls -l ${{ github.workspace }}
        shell: bash

      - name: Substitute current sha into yaml
        id: yaml-sub
        uses: Opentrons/opentrons-emulation@working-with-other-repos
        with:
          command: yaml-sub
          substitutions: >-
            [
              ["otie", "source-location", "${{ github.sha }}"]
            ]
          input-file: ${{ github.workspace }}/ot3-firmware/emulation_setups/ot3_only.yaml

      - name: Echo Output
        run: echo "${{ steps.yaml-sub.outputs.modified-yaml }}"
