on: [push]

jobs:
  ot3-emulator:
    runs-on: ubuntu-latest
    name: OT-3 Emulator
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Opentrons/ot3-emulator@v1
        with:
          ot3-firmware-commit-id: {{ github.sha }}