on:
  pull_request:
  workflow_dispatch:


env:
  ci: 1

jobs:
  ot3-emulator:
    runs-on: "ubuntu-20.04"
    name: OT-3 Emulator
    steps:

      - name: Checkout opentrons-emulation repo
        uses: actions/checkout@v3
        with:
          repository: Opentrons/opentrons-emulation
          ref: release-v2.3.3

      - name: Checkout ot3-firmware repo
        uses: actions/checkout@v3
        with:
          path: ot3-firmware
          
      - name: Checkout opentrons repository
        uses: actions/checkout@v3
        with:
          repository: "Opentrons/opentrons"
          path: opentrons

      - name: Setup Emulation
        uses: Opentrons/opentrons-emulation@release-v2.3.3
        with:
          cache-break: ${{ github.event.inputs.cache-break }}
          command: setup-python-only

      - name: Substitute current sha into yaml
        id: sub-step
        uses: Opentrons/opentrons-emulation@release-v2.3.3
        with:
          command: yaml-sub
          substitutions: >-
            [
              ["otie", "source-location", "${{ github.sha }}"]
            ]
          input-file: ${{ github.workspace }}/ot3-firmware/emulation_setups/ci/ot3_only.yaml
          output-file-location: ${{ github.workspace }}/output.yaml


      - name: Build Emulator
        uses: Opentrons/opentrons-emulation@release-v2.3.3
        with:
          command: setup
          input-file: ${{ github.workspace }}/output.yaml

      - name: Run Emulation
        uses: Opentrons/opentrons-emulation@release-v2.3.3
        with:
          command: run
          input-file: ${{ github.workspace }}/output.yaml

      - name: Give it some time to start up
        run: sleep 10s

      - name: Test Emulation
        run: "curl --request GET --header 'opentrons-version: *' http://localhost:31950/modules"

      - name: Teardown Emulation
        uses: Opentrons/opentrons-emulation@release-v2.3.3
        with:
          input-file: ${{ github.workspace }}/output.yaml
          command: teardown
