name: "Sensors build/test"
on:
  pull_request:
    paths:
      - "i2c/**"
      - "include/motor-control/core/**"
      - "motor-control/core/**"
      - "include/i2c/**"
      - "common/**"
      - "include/common/**"
      - "include/sensors/**"
      - "common/**"
      - "include/can/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
  push:
    paths:
      - "include/motor-control/core/**"
      - "motor-control/core/**"
      - "i2c/**"
      - "include/i2c/**"
      - "common/**"
      - "include/common/**"
      - "include/sensors/**"
      - "common/**"
      - "include/can/**"
      - "cmake/*"
      - "!cmake/Arduino*"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".clang-format"
      - ".clang-tidy"
      - ".github/workflows/sensors.yaml"
    branches:
      - "*"
    tags:
      - "sensors@*"
  workflow_dispatch:

env:
  ci: 1

defaults:
  run:
    shell: bash

jobs:
  cross-compile-check:
    name: "Cross-Compile/Check"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "actions/cache@v3"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}
      - name: "Configure"
        run: cmake --preset=cross . -DCMAKE_BUILD_TYPE=debug
      - name: "Format"
        run: cmake --build ./build-cross --target sensors-format-ci
  host-compile-test:
    name: "Host-Compile/Test"
    runs-on: "ubuntu-20.04"
    timeout-minutes: 10
    steps:
      - name: Update and install gcc-10 & g++-10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Checkout ot3-firmware repository
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          path: ot3-firmware

      - name: Checkout opentrons repository
        uses: actions/checkout@v3
        with:
          repository: "Opentrons/opentrons"
          path: opentrons

      - name: Cache stm32-tools
        uses: "actions/cache@v3"
        with:
          path: "./stm32-tools"
          key: ${{ runner.os }}-${{ hashFiles('**/cmake/*') }}-${{ secrets.CACHE_VERSION }}

      - name: "Configure"
        run: cmake --preset=host-gcc10 .
        working-directory: ot3-firmware

      - name: 'Build and test'
        run: cmake --build ./build-host --target sensors-build-and-test
        working-directory: ot3-firmware
